name: moc_firebase
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.1
  cloud_firestore: ^4.5.3
  firebase_ui_firestore: 1.4.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true